#!/usr/bin/env node
"use strict";

const Ethers = require("ethers");
const Fs = require("fs");
const TimersPromises = require("timers/promises");

// Load and return a compiled smart contract in combined JSON format.
function loadContract(name, compiled, solName) {

  if (!compiled) {
    const file = name + ".compiled";
    console.log("Reading compiled contract (combined JSON):", file);
    compiled = JSON.parse(Fs.readFileSync(file));
  }

  solName ||= name + ".sol";
  const findFunc = solName.indexOf(":") > -1 // contract name included?
                   ? x => x == solName
                   : x => x.match(`(^|/)${solName}:`);
  const nameKey = Object.keys(compiled.contracts).find(findFunc);
  if (!nameKey)
    throw `Smart contract "${solName}" not found in the JSON file`;

  const contractInfo = compiled.contracts[nameKey];
  const abi = typeof contractInfo.abi == "string"
              ? JSON.parse(contractInfo.abi) : contractInfo.abi;
  const bin = Buffer.from(contractInfo.bin, "hex");
  return [ abi, bin ];
}

// Mint tokens using given contract if it looks like a token contract.
async function mintMaybe(name, contract) {

  if (!name.match(/(^|[^a-z])token([^a-z]|$)/))
    return;

  const amount = Number(process.env.GORA_DEV_DEPLOY_TOKEN_MINT_AMOUNT)
                 || 10_000_000;
  if (!amount)
    return;

  console.log(`Token contract detected, minting "${amount}" token(s)`);
  await TimersPromises.setTimeout(1000);
  const decimals = await contract.decimals();
  await (await contract.mint(BigInt(amount) * 10n**decimals)).wait();
}

// Deploy a compiled smart contract.
async function deploy({ apiUrl, name, solName, addrFile, compiled, signer, args }) {

  let provider
  if (signer)
    provider = signer.provider;
  else {
    console.log("EVM API endpoint:", apiUrl);
    provider = new Ethers.JsonRpcProvider(apiUrl, null, {
      pollingInterval: 1000,
      polling: true,
    });
  }
  console.log("At block:", await provider.getBlockNumber());

  if (!signer) {
    const keyFile = process.env.GORA_DEV_EVM_DEPLOY_KEY || "deploy_key.txt";
    if (Fs.existsSync(keyFile)) {
      console.log(`Reading signer's private key from "${keyFile}"`);
      const privKeyHex = Fs.readFileSync(keyFile, "utf8");
      signer = new Ethers.NonceManager(new Ethers.Wallet(privKeyHex, provider));
    }
    else {
      console.log("No key file, getting a signer automatically");
      signer = await provider.getSigner();
    }
  }

  const signerAddr = await signer.getAddress();
  const balance = await provider.getBalance(signerAddr);
  console.log(`Signer "${signerAddr}" with balance "${balance}"`);

  const constrArgs = args || [];
  for (const varName in process.env) {
    const prefix = "GORA_DEV_EVM_DEPLOY_CONSTR_ARG_";
    if (varName.startsWith(prefix))
      constrArgs[Number(varName.substr(prefix.length))] = process.env[varName];
  }

  solName ||= name + ".sol";
  const [ abi, bin ] = loadContract(name, compiled, solName);
  await TimersPromises.setTimeout(1000);

  console.log(`Deploying "${solName}" with ${constrArgs.length || 'no'} argument(s)`);
  const factory = new Ethers.ContractFactory(abi, bin, signer);
  const contract = await factory.deploy(...constrArgs);
  await contract.waitForDeployment();

  const addr = await contract.getAddress();
  console.log("Deployed to:", addr);

  addrFile ||= name + ".addr";
  console.log("Writing address to:", addrFile);
  Fs.writeFileSync(addrFile, addr);

  mintMaybe(name, contract);
  return contract;
}

if (module.parent) {
  Object.assign(exports, { deploy, loadContract });
  return;
}

if (process.argv.length < 4) {
  console.log("Usage: node deploy.js <node URL> <contract JSON file> [address output file] [solidity file name]");
  return;
}

const [ , , apiUrl, name, addrFile, solName ] = process.argv;
deploy({ apiUrl, name, addrFile, solName });
